In [1]:
import pandas as pd

In [3]:
train_df=pd.read_csv('test.csv')
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

**Handling Missing Values**

In [4]:
categorical_fill_none = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu',
                         'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
                         'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
                         'BsmtFinType2', 'MasVnrType']

# Fill missing values for categorical features with 'None'
for column in categorical_fill_none:
    if column in train_df.columns:
        train_df[column] = train_df[column].fillna('None')

# List of numerical columns to fill with 0
numerical_fill_zero = ['GarageYrBlt', 'MasVnrArea']

# Fill missing values for numerical features with 0
for column in numerical_fill_zero:
    if column in train_df.columns:
        train_df[column] = train_df[column].fillna(0)

# Fill missing values for 'LotFrontage' with the median value
if 'LotFrontage' in train_df.columns:
    train_df['LotFrontage'] = train_df['LotFrontage'].fillna(train_df['LotFrontage'].median())

# Fill missing values for 'Electrical' with the mode
if 'Electrical' in train_df.columns:
    train_df['Electrical'] = train_df['Electrical'].fillna(train_df['Electrical'].mode()[0])

# Verify if there are any remaining missing values
print(train_df.isnull().sum().sum())

22

**Encode Categorical Features**

In [5]:
train_df = pd.get_dummies(train_df)

**Feature Scaling**

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numerical_features = train_df.select_dtypes(include=['int64', 'float64']).columns
train_df[numerical_features] = scaler.fit_transform(train_df[numerical_features])

**Feature Engineering**

In [7]:
train_df['TotalSF'] = train_df['TotalBsmtSF'] + train_df['1stFlrSF'] + train_df['2ndFlrSF']

In [8]:
train_df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,TotalSF
0,-1.730864,-0.874711,0.567330,0.363929,-0.751101,0.400766,-0.340945,-1.072885,-0.563316,0.063273,...,False,False,True,False,False,False,False,True,False,-1.800496
1,-1.728490,-0.874711,0.615963,0.897861,-0.054877,0.400766,-0.439695,-1.214908,0.047057,1.063027,...,False,False,True,False,False,False,False,True,False,0.296970
2,-1.726115,0.061351,0.275532,0.809646,-0.751101,-0.497418,0.844059,0.678742,-0.563316,0.772989,...,False,False,True,False,False,False,False,True,False,0.050994
3,-1.723741,0.061351,0.470064,0.032064,-0.054877,0.400766,0.876976,0.678742,-0.450284,0.357706,...,False,False,True,False,False,False,False,True,False,-0.013249
4,-1.721367,1.465443,-1.232092,-0.971808,1.337571,-0.497418,0.679475,0.394694,-0.563316,-0.387166,...,False,False,True,False,False,False,False,True,False,0.063191

In [9]:
test_df=pd.read_csv('train.csv')
test_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

Using this data a prediction model can be built to predict house prices.